### ISSUE TITLE
Improve lighthouse score

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#108]
![image](https://github.com/nptscot/nptscot.github.io/assets/15819577/06ca57f4-c2b4-41bd-ac94-4f8bb98432c8)

First Contentful Paint 3.5 s
Largest Contentful Paint 4.1 s
Total Blocking Time 1,210 ms
Cumulative Layout Shift 0.001
Speed Index 3.8 s

![image](https://github.com/nptscot/nptscot.github.io/assets/15819577/abc63fe2-a078-4236-9d65-9efa19b90779)

**Comment by Robinlovelace** [comment]
Good to see these results! Any ideas of how to improve the scores?

**Comment by mem48** [comment]
Yes, lots of things that can be done

**Comment by mem48** [comment]
Mostly a good clean of the code and tweaking the load order. Won't get 100% as the rnet is too large. But will get some improvements

**Comment by mem48** [comment]
fa-solid-900.woff2 can be slimmed down https://stackoverflow.com/questions/5988013/how-to-edit-woff-font-files-offered-by-google-webfonts 
Saving 147KB

**Comment by mem48** [comment]
![image](https://github.com/nptscot/nptscot.github.io/assets/15819577/b2d4e601-f2a8-4ca6-8f5b-c55a151a85c8)

**Comment by mem48** [comment]
Running out of ideas, as most of the performance problems are due to the rendering of the map. Its just not a quick thing to load

**Comment by mem48** [comment]
@mvl22 taggin you in this issue, so you are aware of the past scores and existing changes made to improve performance.
