### ISSUE TITLE
Close help by clicking outside the box

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#110]

**Comment by mvl22** [comment]
Yes, I've run into this usability issue also - click outside the box is an implied close in most UIs.

Will pick this one up as the refactoring proceeds. I expect to write a generic handler to manage these, so the welcome screen also does the same.

**Comment by mvl22** [comment]
Fixed in 9dff2aa7f7c0f55a57a7afa1635f5bd834ce3845, which migrates the help modal to the standard modal handler (which includes support for click-outside and escape-key close methods).
