### ISSUE TITLE
Change route network visualisation parameters depending on purpose

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#117]
Currently the width and colour scales are fixed, meaning that the primary school trips for example are hard to see. Idea discussed with @mem48 is that we could make the scale for width vary in proportion to the max (or 90% percentile) ratio of `max_commute / max_purpose`

**Comment by mem48** [comment]
The main issue I can see is that the max/min values are hard to get. E.g. you would have to check the whole pmtiles file. So we would have to hard code the ranges for each type of rnet and the update the website for each build

**Comment by Robinlovelace** [comment]
Gould we have a config file that contains the multipliers, e.g.

| Purpose | Multiplier |
|=======|====|
| All | 1 |
| Commute | 2.5 |
| School, primary | 9 |
| School, secondary | 3 |

**Comment by mvl22** [comment]
Yes, if you can build a JSON file containing definitions I can incorporate its data into the display logic.

Ideal structure is too early to tell at this point, but if you can produce something we can adjust it later as the site moves towards having declarative definitions for layers.

**Comment by mem48** [comment]
Could his add a big performance overhead. Adding one more calculation for every segment in the rnet would be a lot of extra calculations in total. And the very complex line width logic is already quite a burden.

**Comment by Robinlovelace** [comment]
Thoughts @mvl22? It doesn't seem that much to me.

**Comment by Robinlovelace** [comment]
@mvl22 could you provide a sense of how much time it would take to do this? We should decide if it's a Phase 2 or Phase 3 task based on information.

**Comment by mvl22** [comment]
My thoughts:

- I can see the value of this but I think it would have the **major** disadvantage of being misleading, in that if, say, the schemes for schools and commuting have their ranges aligned, this would misleadingly imply similar levels of cycling between these. There is value in having the different usage types being the same scale as it does enable a sense of comparative levels of cycling between them. The lines are still visible between scenarios, just less prominent - I think users do probably understand that they can zoom in and see in a bit more detail.
- There would need to be manual definitions decided if done.
- I doubt there is much computation overhead here, as the style definitions are compiled up-front; most of the delay will be simply the data volume.
- If changes were needed, this would need to be done in [the `rnetStyling` callback in the dataset definitions](https://github.com/nptscot/nptscot.github.io/blob/dev/src/datasets.js#L675-L750). I can see this getting a bit complicated, but it is doable. As shown, the callback does have access to the UI parameters.

**Comment by Robinlovelace** [comment]
Closing for now in that case.
