### ISSUE TITLE
Remove version from splash page, focus on date (e.g. v2023-12-18)

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#119]
As discussed with @Mattpdavis and @anguscalder.

**Comment by Robinlovelace** [comment]
Reopening because the version number is still there:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/9b7ccd3b-b2d6-4cf3-9c05-da1b7e2b82b1)

**Comment by Robinlovelace** [comment]
Looking at this now. Heads-up @mem48

**Comment by Robinlovelace** [comment]
Illustration of fix hosted locally, just pushed:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/96cd1a82-b6b7-44b5-ba6c-53ae0180f83b)

**Comment by Mattpdavis** [comment]
Visible on Github but note duplication of url 
(NPT Scotland, hosted at [npt.scot](https://www.npt.scot))
