### ISSUE TITLE
Tiles do not load in development scenario: CORS policy not enabled for 127.0.0.1:5500

### ISSUE THREAD

**Issue by mvl22** [nptscot/nptscot.github.io#124]
Tile layers do not load due to a CORS error on running the site locally:

`Access to fetch at 'https://nptscot.blob.core.windows.net/rastertiles/dem/6/31/19.webp' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Given that the README recommends using a built-in server at http://127.0.0.1:5500, it would be sensible for the nptscot.blob.core.windows.net domain to allowlist http://127.0.0.1:5500 as an allowed client for CORS purposes. Please add it in the settings there.

**Comment by Robinlovelace** [comment]
Good spot @mvl22 will try to assign you just to check if you're in the team. Probably one for @mem48 if you get a chance.

**Comment by Robinlovelace** [comment]
Update: you're in :rocket:

**Comment by Robinlovelace** [comment]
Solution: use the port number, let us know if  you need to know what that is.

**Comment by mvl22** [comment]
Thanks, working now.
