### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#127]
We should add logos to the website in an appropriate place, I'm not sure where yet, thoughts welcome, and tracking the issue here. Discussed with @mvl22 yesterday.

**Comment by Robinlovelace** [comment]
University of Leeds:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/a5cc63bf-c848-4c33-9dde-243085e3fb3f)

**Comment by Robinlovelace** [comment]
Sustrans Scotland (pending any suggestions from @anguscalder or @Mattpdavis )

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/0717b2ca-3bf9-401d-b2c5-2d0953a91d30)

**Comment by Robinlovelace** [comment]
Transport Scotland:

https://en.wikipedia.org/wiki/Transport_Scotland#/media/File:Transport_Scotland_logo.svg

**Comment by Robinlovelace** [comment]
CycleStreets, I think you can supply that one Martin!

**Comment by Robinlovelace** [comment]
2 options jump to mind, does the 'splash page' when you land seem like a good option?

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/ba1db63e-85e1-4384-9a08-992b9b68c1f4)

**Comment by mvl22** [comment]
First go at this, which I think works fine. I've used the same logo order as you posted, but please do suggest any changes.

![Screenshot 2024-02-12 at 19 37 11](https://github.com/nptscot/nptscot.github.io/assets/361423/1b4faf21-eac6-4b0d-8859-7a5c8092c2a9)

**Comment by Robinlovelace** [comment]
Looks great to me. For new features can you put them in separate PRs to differentiate from general refactoring @mvl22 ?

**Comment by Robinlovelace** [comment]
Now on test website so closing for now.

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/c8f1535f-eebb-4793-9969-ae695e8bfa8e)
