### ISSUE TITLE
Replace OpenCycleMap with vector data

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#135]
Not high piorirty but something to think about.

Currently the basemap option is for the Open Cycle Map uses Thunderforest raster tiles See https://github.com/nptscot/npt/issues/51 

But protomaps has a method for making pmtiles from OSM https://github.com/protomaps/basemaps 

Switching to a self hosted pmtiles for the OSM based map would have two advantages:

1) No reliance on 3rd part service (but would pay for storage of pmtiles)
2) Could have multiple OSM based styles

I think point 2 is the key one as the OpenCycleMap is useful for showing location of infrastructure, but is otherwise a very noisy base map. It would be nice to have something more like the OS basemaps currently in the tool, but also highlight the cycling infrastructure.

On the downside I don't think mapbox styles can do the thing where the road is one colour but the edge is a different colour if there is a cycle lane. 

![image](https://github.com/nptscot/nptscot.github.io/assets/15819577/09f3e3ac-82f5-4f7b-8b1e-01671dd78597)

So some futher investigation is needed.

**Comment by Robinlovelace** [comment]
Good example of vector tiles for open cycling infrastructure data is ATIP's browse page:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/00011e4a-d310-4bf1-b70f-d3c49fd00a6e)

Source: https://acteng.github.io/atip/browse.html?style=dataviz#12.54/53.79201/-1.52591

Code: https://github.com/acteng/atip/

**Comment by mvl22** [comment]
> I think point 2 is the key one as the OpenCycleMap is useful for showing location of infrastructure, but is otherwise a very noisy base map.

It is, but it has the unique advantage of showing official (signed on-street) routes.

Generally I recommend setting 0.7 opacity when using it as a basemap. That washes it out slightly but gives a good balance between the official routes it shows and any foreground data lines.


> It would be nice to have something more like the OS basemaps currently in the tool, but also highlight the cycling infrastructure.

Bear in mind that writing a stylesheet isn't free. It's a very large amount of time/work to do properly. Thunderforest have spent years developing their cartgography.

**Comment by mem48** [comment]
> Generally I recommend setting 0.7 opacity when using it as a basemap. That washes it out slightly but gives a good balance between the official routes it shows and any foreground data lines.

That might not work for NPT as the canvas background is not white. Its a funky gradient of colours so that in 3D mode the sky is blue but if you go really low angle the sun sets.![Screenshot_20240120-140200_Firefox.jpg](https://github.com/nptscot/nptscot.github.io/assets/15819577/c9aa766e-648b-45f9-90f2-78979af978ee)

**Comment by mvl22** [comment]
I was referring to the OpenCycleMap tile layer. Opacity can be set on a per layer basis. Obviously this shouldn't be applied to other layers or to the sky canvas.

**Comment by mvl22** [comment]
I've reduced the opacity of the OCM tiles in 08f9785dde4c91b877cc5ed67f45ec0abea344c3 so they work better now as a background.

I suggest this ticket be closed, as I suspect spending months emulating the OpenCycleMap detailed cartography in vector format is beyond the scope of this project.

**Comment by Robinlovelace** [comment]
:+1: great stuff, I think reducing the oppacity is a good fix and agreed re emulating established product, we don't need to invent the wheel!
