### ISSUE TITLE
Lower-cased gradient/quietness fields to be reflected in the website code

### ISSUE THREAD

**Issue by mvl22** [nptscot/nptscot.github.io#141]
There are various cases of Gradient -> gradient and Quietness -> quietness to be updated in the definitions, e.g. 
https://github.com/nptscot/nptscot.github.io/blob/refactor/src/datasets.js#L603-L605

Pending
https://github.com/nptscot/npt/pull/397

**Comment by Robinlovelace** [comment]
This should be fixed after the next full build. Work in progress.

**Comment by Robinlovelace** [comment]
Heads-up @mvl22, @wangzhao0217 has just released a load of new data for you. Please can you check here, all fields should be lower case now: https://github.com/nptscot/npt/releases/tag/v2024-02-14

**Comment by Robinlovelace** [comment]
I've just double checked the files in that release and indeed lower case gradient is in there, fixed right @mvl22 ? However, we need to do another full build because that's just a test one for Edinburgh.

**Comment by mvl22** [comment]
Glad to hear it worked. Just need to know when the new dataset is on the server, so these two URLs can be updated.

https://github.com/nptscot/nptscot.github.io/blob/dev/src/datasets.js#L7-L25
