### ISSUE TITLE
Broadband void value change to be reflected in the website code

### ISSUE THREAD

**Issue by mvl22** [nptscot/nptscot.github.io#142]
The definitions currently use 0 as the void value for broadband at
https://github.com/nptscot/nptscot.github.io/blob/refactor/src/datasets.js#L310

Pending
https://github.com/nptscot/npt/issues/385

When this is in place, merging in the definitions file of `lineColours` and `legends` should be possible.

**Comment by Robinlovelace** [comment]
Why does it say that

```js
// #!# Currently zero is used for voids - data should be changed to use known constant e.g. -9999
```

?

As outlined in the other issue, 0 means 0 as far as we can tell, so shouldn't it be:

```diff
- 				'#fff7ec', 0.01,		// #!# Currently zero is used for voids - data should be changed to use known constant e.g. -9999
+ 				'#fff7ec', 0.0,		// lowest value including 0
```

??

**Comment by mvl22** [comment]
0.01 is in Malcolm’s original code. I haven’t changed it. My understanding is that this value was being used because zero represented a void value. So I requested that a real void value be used in the data, as otherwise genuine zero cannot be represented.

Perhaps @mem48 could comment as I think this is the third time this question has been asked.

**Comment by Robinlovelace** [comment]
Yes it has gone round a few times. My suggestion is to change it to 0, with no null value, as I said, unless we hear otherwise.
