### ISSUE TITLE
Layer state permalinks

### ISSUE THREAD

**Issue by mvl22** [nptscot/nptscot.github.io#147]
Layer state is currently not reflected in the URL, so sending a link to another person will lose this. Therefore, the URL should contain the layer list.

To do this properly, using [HTML5 History](https://developer.mozilla.org/en-US/docs/Web/API/History_API), this will require a rewriting solution, as otherwise `/layer1,layer2/` (or whatever) will not exist on the server; it needs to be internally rewritten to `/`.

A hash-based solution is possible, but this would firstly require reimplementing the Mapbox GL JS hash mode manually.

**Comment by mvl22** [comment]
This is now implemented, to the level of enabled layers and map position within the hash state.

Future work will implement parameter state within layers.

> A hash-based solution is possible, but this would firstly require reimplementing the Mapbox GL JS hash mode manually.

These were both implemented.

**Comment by Robinlovelace** [comment]
Good time for me to test locally @mvl22 ? Will aim to test today.
