### ISSUE TITLE
Test new data locally

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#156]

**Comment by mvl22** [comment]
I think you need to check that the building is creating data at all zoom levels:

![Screenshot 2024-03-11 at 18 52 07](https://github.com/nptscot/nptscot.github.io/assets/361423/1230ee9b-ed78-42ee-8ce2-1b35c4dc9bb9)

**Comment by Robinlovelace** [comment]
Probably just due to all data fitting nicely in 1 tile?

**Comment by Robinlovelace** [comment]
But yeah I don't know why that is, and maybe something in it...
