### ISSUE TITLE
Tweak accordion state

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#162]
Following layer-specific URLs (#147) and building on comments in https://github.com/nptscot/npt/issues/391#issuecomment-1994183178 this issue can track the following:

> [reworking] the accordion to have a proper hierarchical relationship between the titles, the layer-enabling buttons and the controls within layers

**Comment by Robinlovelace** [comment]
Still planned @mvl22? Would be great to see a design for this. Closing for now as it feels a bit stale and it's not clear what the outcome will be, I think this came from Martin, needs more input to revive IMO.

**Comment by mvl22** [comment]
Yes, this is important, so we can remove some confusion.

Basically the problems are:

- Enabled layers, following permalink implementation in the URL, don't get their accordion sections auto-opened, which is inconsistent.
- Controls such as layers, 'Simplified', 'Dasymetric' should all be grayed out when a layer is not selected, as this confusingly suggests they are active even though the layer is not enabled.

This is low-hanging fruit so I'll blitz this next.

**Comment by Robinlovelace** [comment]
Just checking in on various issues, this sounds like the priority for now, right @mvl22 ? Any indication of how much time it will take very welcome.
