### ISSUE TITLE
Dasymetric switch

### ISSUE THREAD

**Issue by richybu** [nptscot/nptscot.github.io#164]
The dasymetric switch shouldnt work if the 'show layer' checkbox isnt selected as otherwise its confusing and looks like its not doing anything.

**Comment by mvl22** [comment]
Thanks - yes, agreed.

It is planned for controls that relate to a disabled layer all to be grayed out. This will be implemented as part of #162.

**Comment by Robinlovelace** [comment]
Still planned? Closing for now as it depends on stale issue #162, happy for this to be re-opened when we have more information.

**Comment by mvl22** [comment]
It's the same thing as #162 as you note, and will be picked up within that, so good to close this issue.
