### ISSUE TITLE
Route network shown by colour and width

### ISSUE THREAD

**Issue by richybu** [nptscot/nptscot.github.io#165]
The automatic Route Network line colour dropdown for the page is People Cycling Per day. Its very confusing at first as its normal to assume the colour and width mean different things (leaving me to assume for a while that width was road size), but they actually show the same thing. The explanation is buried deep in the help page. Whilst i can understand why you have done this I think you should either make this very explicit or have the Line colour dropdown set to 'None' when the page is first loaded so as not to confuse people (though it doesnt look as interesting or show off the tool as well)

**Comment by Robinlovelace** [comment]
Suggestion: let's make colour cycle friendliness. Thoughts @mvl22, @Mattpdavis and @anguscalder?

**Comment by Robinlovelace** [comment]
I agree but this would need sign-off by Sustrans so marking as not planned for now.

**Comment by anguscalder** [comment]
Hi All, understand the initial comment but on balance I think best if we just stick to existing colour & width both refelcting flow - perhaps we could amend the pop up notes to make it clearer that both are a reflectio of flow

**Comment by Robinlovelace** [comment]
@mvl22 can you clarify what the action is on this in relation to re-opening this, to amend the pop-up?

That seems more like a new issue to me.

**Comment by mvl22** [comment]
> can you clarify what the action is on this in relation to re-opening this, to amend the pop-up

'perhaps we could amend the pop up notes to make it clearer that both are a reflectio of flow'

**Comment by mvl22** [comment]
Actually there was an update earlier which I think clarifies this.

'The thickness of the lines in the route network is also defined by the number of cycle trips, with thicker lines representing more people cycling.'

now stands out as a separate paragraph and the section before it is clearer.
