### ISSUE TITLE
Coherent network section on manual page

### ISSUE THREAD

**Issue by richybu** [nptscot/nptscot.github.io#169]
Once test web app version is implemented, add a 'Cohesive Network' section to the manual page between Route Network Filters and Data Zones, explaining in more detail what it shows, how it was created, and the key.

**Comment by Robinlovelace** [comment]
:+1: to that.

**Comment by Robinlovelace** [comment]
Self assigned for now, may need to help or to re-assign to someone else in future.

**Comment by Robinlovelace** [comment]
We need to get the cohesive network working first..

**Comment by mvl22** [comment]
Can this text now be added?

https://github.com/nptscot/nptscot.github.io/blob/dev/manual/index.md
is the file.

**Comment by Robinlovelace** [comment]
Yes good plan. @wangzhao0217 you happy to give that a go? Any questions let us know.

**Comment by mvl22** [comment]
> This should be a quick fix. Can you give it a quick bash @mvl22?

Done; I've created what text I could based on the documentation around the organisation's repos, but it needs you to add some more detail probably.

**Comment by mvl22** [comment]
It might be good to say a little about how the calculation was done 'under the hood', i.e. a brief layperson's explanation of the algorithm. I think many people will wonder, so would be good for one of your team to turn that into a couple of sentences that could be added at:

https://github.com/nptscot/nptscot.github.io/blob/dev/manual/index.md?plain=1#L249-L257

**Comment by Robinlovelace** [comment]
One for @wangzhao0217

**Comment by mvl22** [comment]
I see extra text was indeed added in a38ae370e57114c4818d213832e08b7b228e73c7, which is is excellent - great work.
