### ISSUE TITLE
Dasymetric maps

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#17]
Implementing dasymetric mapping similar to 

https://www.ons.gov.uk/census/maps/choropleth/population/household-composition/hh-family-composition-4a/one-person-household

Example:

![image](https://user-images.githubusercontent.com/15819577/221434680-41ee0376-4756-4203-b20e-6d34d80cc206.png)

Map colours the buildings in a zone rather than the zone itself. Which makes it easier to see rnet/zones/basemap at the same time.

Verses current zones

![image](https://user-images.githubusercontent.com/15819577/221434829-b61b8041-2be8-4062-8aca-511a47946ad9.png)

**Comment by Robinlovelace** [comment]
Great idea. This technique was I believe pioneered by @oobrien e.g. as documented here: https://discovery.ucl.ac.uk/id/eprint/1469169/6/O'Brien_1469169.pdf 

In any case, big thumbs up from me on this.

**Comment by mem48** [comment]
Yes, but their approach (and the ONS's) relies on transparent raster tiles which allow the choropleth map to peak through.

My approach is fully vectorised https://twitter.com/DrMalcolmMorgan/status/1629848619728732161 so we can do fun things like this:
 
![dasymetric](https://user-images.githubusercontent.com/15819577/221435252-23e9292e-c131-4641-9866-b8b94c327c98.JPG)

**Comment by Robinlovelace** [comment]
OK so the buildings have the colour of the attribute? interesting!
