### ISSUE TITLE
Test new rnet

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#177]

**Comment by Robinlovelace** [comment]
Heads-up @mvl22 I've uploaded the new data, am testing locally with changes in #178, but no data shown:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/54ac6056-7c0b-4cf9-9bd2-a7a375a80277)

However, the data is there and works on PMTiles test site: https://nptscot.blob.core.windows.net/pmtiles/rnet_2024-04-27.pmtiles

Any ideas?

**Comment by Robinlovelace** [comment]
Cc @mem48 in case you can reproduce this issue, any luck?

**Comment by mvl22** [comment]
Has the field name changed?

**Comment by Robinlovelace** [comment]
No cacheing. Yeah maybe field name issues..

**Comment by Robinlovelace** [comment]
![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/8c6ac657-31c6-4d71-84a4-19f3a9b91175)

Merging #156 into #178 fixes it :tada:
