### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by mvl22** [nptscot/nptscot.github.io#206]
I believe the old branches are obsolete, and should be deleted:

https://github.com/nptscot/nptscot.github.io/tree/26-reorder-admin-boundaries

https://github.com/nptscot/nptscot.github.io/tree/89-update-manual-to-mention-2-layer-types

https://github.com/nptscot/nptscot.github.io/tree/179-show-new-cohesive-network-data

**Comment by Robinlovelace** [comment]
Will do.
