### ISSUE TITLE
Colour coherent network by value

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#209]
As shown below we have the value:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/8e146f68-4e98-494d-a547-bd8bdc3e817d)

**Comment by Robinlovelace** [comment]
Nudge on this @mvl22, do you have everything you need to work on this? Latest data has the value I think.

**Comment by mvl22** [comment]
Excellent. Can you clarify which of the two files should have it? I see we have switched filenames back and forth.

**Comment by Robinlovelace** [comment]
The file currently on dev branch should have it. If not let me know.

**Comment by mvl22** [comment]
![Screenshot 2024-06-22 at 16 25 19](https://github.com/nptscot/nptscot.github.io/assets/361423/0656ce91-07b0-4f6e-8316-77fb392c97fc)
