### ISSUE TITLE
Tutorial mode

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#21]
See https://mahere.at.govt.nz/FutureConnect/ for ideas

**Comment by mem48** [comment]
I've been thinking about this:

1) It will be quite a lot of work to set up
2) It's not something you should do until the UI is 100% finalised. 

So I'm going to suggest this is something we leave until the full launch later in the year.

**Comment by Robinlovelace** [comment]
Agreed, a lot of work.
