### ISSUE TITLE
Placename search includes locations outside Scotland

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#214]
It's great that there *is* a filter on placenames but seemingly for all of GB, not Scotland. Demo: try typing "Paris" into the search bar. It shows you something like this:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/a74d5da7-a84c-436a-aee9-11d223447a12)

Source: https://nptscot.github.io/#/coherentnetwork/#6/54.113/0.525

**Comment by mvl22** [comment]
Frankly I'd like to rework the way the geocoder works. The UI is not intuitive, and is different to most other sites.

Currently:

- There is no search-as-you-type - you have to press return which is not obvious
- Entering a location that does match takes you to the first result
- There is a sort of drop-down but it appears sporadically.

Instead the UI should be the same as on e.g. bikedata.cyclestreets.net:

- Results come up as you type
- The map should not move until a location is selected
- Standard keyboard navigation should be applied.

I'll start a ticket for this, under phase 3.

**Comment by Robinlovelace** [comment]
Agree re. wider issues. Is this one a quick fix in the meantime? Will create a new Phase 3 milestone.

**Comment by mvl22** [comment]
Yes, currently researching. Sorry, meant to say then got distracted by adding the new issue.

Nominatim supports a bounded search by bbox. So this will catch some of Ireland as well. There is no countrycode for Scotland under the ISO system, so it cannot be limited that way.

**Comment by Robinlovelace** [comment]
Great stuff :+1:

**Comment by mvl22** [comment]
Are you happy with this bbox as the limited area?

http://bboxfinder.com/#54.576074,-7.957465,61.147476,-0.150894

**Comment by Robinlovelace** [comment]
Great fix Martin!

**Comment by Robinlovelace** [comment]
Tested:

![Uploading image.png…]()
