### ISSUE TITLE
Geocoder UI needs reworking

### ISSUE THREAD

**Issue by mvl22** [nptscot/nptscot.github.io#218]
We should rework the way the geocoder works. The UI is not intuitive, and is different to most other sites.

Currently:

- There is no search-as-you-type - you have to press return which is not obvious
- Entering a location that does match takes you to the first result
- There is a sort of drop-down but it appears sporadically.

Instead the UI should be the same as on e.g. bikedata.cyclestreets.net:

- Results come up as you type
- The map should not move until a location is selected
- Standard keyboard navigation should be applied.

**Comment by Robinlovelace** [comment]
I think this is likely to be a Phase 3 issue, not urgent, but agree.

**Comment by mvl22** [comment]
Should be all much better now, upon approval of #255.

**Comment by Robinlovelace** [comment]
Great stuff, thank you Martin. Will aim to test, provide feedback, and hopefully merge tomorrow.
