### ISSUE TITLE
Change existing cycle infrastructure layer display order

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#224]
Currently we have Mixed traffic elements obscuring the view of the more important cycle infra layers:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/bda3677b-5135-4595-a91c-dd234cca3f1d)

Source: https://nptscot.github.io/#/clos/#10.34/55.9764/-3.2994

The order should be the same as the legend with the Mixed traffic links at the bottom (first to be displayed maybe).

We could try to fix this in the backend codebase and indeed have an issue tracking it: https://github.com/nptscot/npt/issues/501

As documented there, because 

- Separated (should go top)
- Roadside...
- Cycle lane
- Mixed ...

Are not in alphabetical order there's no clear way without creating a new field called "Cycle separation hierarchy" or similar. Good news: as far as I can tell you can do this with MapLibre: https://maplibre.org/maplibre-style-spec/layers/#symbol-z-order

Thoughts (when back from travels of course) @mvl22 ?

**Comment by mvl22** [comment]
I'm not sure I understand the problem here, and would welcome clarification.

Surely each line has only one category, i.e. no overlap, and therefore the question z-index order does not arise?

**Comment by Robinlovelace** [comment]
> Surely each line has only one category, i.e. no overlap, and therefore the question z-index order does not arise?

Will share image to show the problem...

**Comment by Robinlovelace** [comment]
![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/626c8968-fa06-4b29-941c-91b90b1edc7a)

Source: https://fosstodon.org/@robinlovelace/112677732132346035

**Comment by Robinlovelace** [comment]
Take a look at this bit @mvl22, see the issue?

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/0f586939-2eb9-46ea-8557-74abdd5c116b)

**Comment by Robinlovelace** [comment]
The immediate question is: quick fix on the frontend side, e.g. with reference to this:

> as far as I can tell you can do this with MapLibre: https://maplibre.org/maplibre-style-spec/layers/#symbol-z-order

**Comment by Robinlovelace** [comment]
> Ah, you are saying that, even though this is a single layer and so there is no overlap, the sideroads rendering is poking over the main roads (or whatever), so we need to set the render order within the layer.
> 
> Yep, I'll get that fixed.

Correct

**Comment by Robinlovelace** [comment]
Can tackle it in backend also if tricky

**Comment by Robinlovelace** [comment]
Less relevant after #254 so closing.

**Comment by mvl22** [comment]
> Less relevant after https://github.com/nptscot/nptscot.github.io/pull/254 so closing.

Agreed, the renderer basically is doing the right thing by default, now we don't have loads of irrelevant lines adding clutter.
