### ISSUE TITLE
Update coherent network

### ISSUE THREAD

**Issue by wangzhao0217** [nptscot/nptscot.github.io#228]
Hi @Robinlovelace and @mvl22,

The latest coherent network can be found here https://github.com/nptscot/outputdata/releases/download/v2024-07-02/combined_coherent_networks_2024-07-02.pmtiles

The updated coherent network has two attributes now: all_fastest_bicycle_go_dutch, and growth.

The client has requested the following changes:

1. The network was previously color-coded based on the group attribute. It should now be colour-coded based on the all_fastest_bicycle_go_dutch attribute. The colour scheme and breaks can be the same as the base layer. 
![image](https://github.com/nptscot/nptscot.github.io/assets/74598734/dcedf523-05d7-40da-97b8-f5f4d490cf33)

2. For the growth attribute, which includes values in the list (1, 2, 3, 4), we need to add a filter to allow slicing based on the growth value.
This is growth = 1, Edingburgh
![image](https://github.com/nptscot/nptscot.github.io/assets/74598734/9dd58bfd-897a-4f36-a26c-614254c86bca)
This is growth = 2, Edingburgh
![image](https://github.com/nptscot/nptscot.github.io/assets/74598734/1c337dc5-ef50-4844-a82b-6b4926332448)

If anything is unclear, let's ask for clarification.

**Comment by Robinlovelace** [comment]
This is a clear and well-written issue, thank you Zhao. Good documentation + issue reports -> quick fixes is the hope, keep us posted Martin on thoughts. A benefit of the change in colourschemes: one less colourscheme for the user to think about and greater consistency across layers.

**Comment by Robinlovelace** [comment]
Nudge on this @mvl22 the geometry looks right but the colours are still outdated: 

![image](https://github.com/user-attachments/assets/84191d17-9461-4053-8e2d-fa95561e591f)

**Comment by wangzhao0217** [comment]
@Robinlovelace @dabreegster Hi all, please find the latest coherent network here: https://github.com/nptscot/outputdata/releases/tag/v2024-08-01

**Comment by dabreegster** [comment]
Thanks. Do you have GeoJSON, GPKG, or another format, even just a sample for one area? pmtiles is meant for rendering only.

**Comment by wangzhao0217** [comment]
Got it , just uploaded GeoJSON to the same release https://github.com/nptscot/outputdata/releases/tag/v2024-08-01
![image](https://github.com/user-attachments/assets/4e236e98-3b5f-42bd-9da3-6a6a253a002e)

**Comment by Robinlovelace** [comment]
A 1 MB .geojson sounds like a good place to start: a LOT of data to process but if it can handle that (I think national) dataset it should be able to handle any of the regional datasets.

**Comment by dabreegster** [comment]
I'm mostly seeing MultiLineStrings. In combined_CN_1 in Edinburgh, one of them looks like this:
![image](https://github.com/user-attachments/assets/f2f3b8be-4f96-4803-a450-2abd6ba8d28f)
A simpler example has "spurs" off a main route:
![image](https://github.com/user-attachments/assets/f4a4271d-4e2c-4a54-99f0-2d2979ae92b9)

The route drawing functionality as it's built now handles LineStrings, not MultiLineStrings.
1) How do you imagine a user editing / selecting / splitting / deleting parts of the multi line strings?
2) Are these generated from line strings at road segment level and getting combined later? Could the input into scheme sketcher not be combined?

**Comment by Robinlovelace** [comment]
These are good questions @dabreegster. I agree, keeping the results as LineStrings will make thing simpler. Ultimately these are based on OS OpenRoads data (more consistent and simpler than OSM geometries), so +1 to being faithful to that data structure, which is provided as LineStrings, right?

**Comment by Robinlovelace** [comment]
@wangzhao0217 do we need to update the network or close for now?

**Comment by Robinlovelace** [comment]
Pending feedback from client.

**Comment by Robinlovelace** [comment]
Closing for now because this issue is not clearly defined and we're awaiting feedback. Can re-open or perhaps better open a new issue when we get a steer on this.
