### ISSUE TITLE
Update to Maplibre 4.5

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#230]
Like https://placebasedcarboncalculator.github.io/ NPT is running on MapLibre 3.6.2  from November 2023 but the latest version is 4.5.0

I've switched to 4.5.0 without any apparent issues. But I did have to also switch to pmtiles 3.0.6 to get it working.

There are not any compelling features to justify an upgrade but the long list of bug fixes are probably worth having. There are some breaking changes listed for version 4, so worth checking carefully before switching.

**Comment by Robinlovelace** [comment]
More broadly, worth thinking about a framework, e.g. svelte-maplibre, now that it's reached a certain level of complexit?

**Comment by Robinlovelace** [comment]
Example of web app built with pmtiles + svelte-maplibre: https://acteng.github.io/atip/browse.html

**Comment by mvl22** [comment]
Fixed in https://github.com/nptscot/nptscot.github.io/pull/233.

**Comment by Robinlovelace** [comment]
Good point Malcolm, thanks for spotting this and re-opening. Over to you @mvl22, hopefully not a big job.

**Comment by mvl22** [comment]
> I have spotted a minor bug from the update there are now two attribution controls

Ah, well spotted. I suspect this could have been a problem before and we didn't spot it.

Fixed in PR #239.
