### ISSUE TITLE
Manual Section Links Don't Work

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#231]
The manual has # sections that change the URL when you click on the table of contents. But you can't use these to make an external link

For example https://nptscot.github.io/manual/#progressivewebapp

**Comment by Robinlovelace** [comment]
That is not expected or usual behaviour so this is a bug. Good spot @mem48, thanks for reporting. Any ideas of the cause @mvl22 ?

**Comment by mvl22** [comment]
Fixed in https://github.com/nptscot/nptscot.github.io/pull/232.
