### ISSUE TITLE
Hotfix to CN layer

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#237]
Split-out from larger issue https://github.com/nptscot/nptscot.github.io/issues/228, this issue is about the things that are broken in the cn currently:

- Meaningless legend
- Out-of-date data

This will be a quick fix, documenting here to keep #228 focussed on wider changes.

**Comment by Robinlovelace** [comment]
Before: #228 

After: 

![image](https://github.com/user-attachments/assets/533ba8c3-4dea-46e2-9b60-08743c8c7ad3)

**Comment by Robinlovelace** [comment]
Source: https://nptscot.github.io/#/coherentnetwork/#8/56.01/-3.27

**Comment by mvl22** [comment]
That fix was good. I'll delete the orphaned colour definitions also in the next commit, just to keep this clean.
