### ISSUE TITLE
Update cn to September build

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#241]
Before: https://nptscot.github.io/#/coherentnetwork/#9.91/55.9673/-3.3105

![image](https://github.com/user-attachments/assets/7d751038-4eef-47af-af22-1ac8f8b4152a)

After...

**Comment by Robinlovelace** [comment]
After:

![image](https://github.com/user-attachments/assets/945be85d-d614-4bd0-a331-fba54fce69b8)

**Comment by wangzhao0217** [comment]
> Source: http://127.0.0.1:4321/#/coherentnetwork/#11.43/55.9242/-3.1583

Robin, you may want to replace the link?

**Comment by Robinlovelace** [comment]
Link updated. Also... do the links to locations work for you? Not working reliably for me.
