### ISSUE TITLE
New Local Authority Overview tab

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#245]
A bit like this would be great:

![image](https://github.com/user-attachments/assets/ef4e1870-fc8b-419d-8ee2-a1a14822e287)

**Comment by mvl22** [comment]
Is the data available for this yet? I presume this is some kind of dashboard of results.

**Comment by Robinlovelace** [comment]
Anything you need from the data side before implementing this @mvl22? Will assign to you for now, should be a quick win that will make the scheme sketch UI more prominent and be a good indication of the direction of travel.

**Comment by mvl22** [comment]
Yes, I'll be sorting this out shortly.

I want to complete migration of all the styling stuff to a unified set of definitions, as they still a bit scattered around from the legacy code. This will obviously be necessary anyway if we are to move to a single unified interface, as we will need the style definitions clearly set out to copy over.

**Comment by Robinlovelace** [comment]
Sounds good.

**Comment by mvl22** [comment]
Are you able to dump out the Local Authorities as a GeoJSON as well as the current PMTiles, with simplified geometries to get the size down? That can then be used to create the listing.

**Comment by Robinlovelace** [comment]
Tagging @wangzhao0217

**Comment by wangzhao0217** [comment]
Hi @mvl22 , just want to check the data you need is GeoJSON and PMTiles files of Local Authorities?

**Comment by mvl22** [comment]
Yes. There is already PMTiles as that is what is shown.

But a general webpage will need a GeoJSON file to read, as PMTiles is obviously not a native web format and needs a mapping framework to interpret it. The GeoJSON can obviously just be read in with normal AJAX and then turned into a listing page.

**Comment by wangzhao0217** [comment]
Please find the data here : https://github.com/nptscot/internal/releases/tag/local_authorities

**Comment by mvl22** [comment]
Can you let me know the URL of this file when it's on the server?

I'd rather not commit data into the web repository.

This file will need the summary attributes added to in future.

**Comment by Robinlovelace** [comment]
> Can you let me know the URL of this file when it's on the server?
> 
> I'd rather not commit data into the web repository.
> 
> This file will need the summary attributes added to in future.

Try this, which deliberately has both LA and region summary data: https://github.com/nptscot/scheme-sketcher/raw/refs/heads/main/assets/boundaries.geojson

See description in the text, including good user of `mapshaper` to avoid using the 1+MB unsimplified geometries in the link Zhao shared: https://github.com/nptscot/scheme-sketcher/tree/main/assets

Currently served at: https://nptscot.github.io/scheme-sketcher/assets/boundaries-3d573d2e.geojson

Source: 

https://nptscot.github.io/scheme-sketcher/

Screenshot: 

![image](https://github.com/user-attachments/assets/7b022256-5f81-47fe-a6db-6b193c181fa9)

**Comment by mvl22** [comment]
In the `la.pmtiles` vector tiles file, could the `kind` (e.g. `LAD` (whatever that means)) and `name` (e.g. `City of Edinburgh`) properties be added? These are present in the equivalent GeoJSON file. This would enable links to be added to the map with popups too.

**Comment by Robinlovelace** [comment]
> In the `la.pmtiles` vector tiles file, could the `kind` (e.g. `LAD` (whatever that means)) and `name` (e.g. `City of Edinburgh`) properties be added? These are present in the equivalent GeoJSON file. This would enable links to be added to the map with popups too.

Yes good idea.

**Comment by Robinlovelace** [comment]
I works:

![image](https://github.com/user-attachments/assets/3ce1bc8f-04c7-4fc4-9ff8-83e550f45f27)
