### ISSUE TITLE
Add regional parlimentary boundaries

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#25]

**Comment by Robinlovelace** [comment]
> Please can we remove the westminster boundaries entirely.

Job done in commit above and shown below

![image](https://user-images.githubusercontent.com/1825120/224469405-5af63e50-4278-4fb2-832a-0bf3a1663967.png)

>  Also keen to add individual settlement boundaries & in the main cities, boundaries of key city centre transport/urban transformation projects ie Edinburgh's LEZ or CCT

Do you have a link to datasets containing this Angus?

Thanks for the feedback.

**Comment by mem48** [comment]
@Robinlovelace please don't do this. Editing the index.html file is not the correct way to fix this issue.

**Comment by mem48** [comment]
@anguscalder I can do this, but is there a reason?/ Do Scottish MP's not have responsibilities for transport in Scotland?

**Comment by mem48** [comment]
Its not a good work around for the user if it wastes time fixing problems that could have been spent on making improvements.

This would have been a 5 min job for me to do, but took me over a hour to work out and rectify what you had done.

**Comment by Robinlovelace** [comment]
It took you an hour to remove 25 lines? 

https://github.com/nptscot/nptscot.github.io/commit/459e2ff65a085bf8e277ea18ec796211ddd543a7

Sorry for causing the hassle in any case, assumed it would be a quick fix.

**Comment by mem48** [comment]
Not to remove the 25 lines. The problem was I was working on something else and getting lots of errors and bugs. I thought it was due to something I had done, and spent ages trying to fix it. It was only much later that I realised that I had not caused the bug.

What you did was like fixing a car with a wobbly wheel by removing the wheel entirely. It might keep going for a while but eventually, it will crash.

**Comment by Robinlovelace** [comment]
Glad you sorted it Malcolm and sorry it caused you so much hassle. Code review and checking the commit history in https://github.com/nptscot/nptscot.github.io/commits/dev should help with debugging, you can always go back to previous commits to find the change that let to a particular error message.

Glad it's fixed now, allowing focus on the other issues, we should have something strong to show on Thursday.
