### ISSUE TITLE
Labelling for trips per day

### ISSUE THREAD

**Issue by mvl22** [nptscot/nptscot.github.io#261]
The interface refers in several places to 'People cycling per day', i.e. cyclists per day.

However, I don't think it's 'people' or 'cyclists' per day strictly, as a return trip would be two trips but one person/cyclist. This is a little confusing.

Can I suggest we change this from 'People cycling per day' to 'Cycle trips per day' throughout? I think that is unambiguous, and it also has the benefit of being slightly shorter.

**Comment by Robinlovelace** [comment]
It's AADT. Cycle trips per day captures that better than 'People cycling per day', and I guess specifically 'Cycle trips per day passing this point in either direction'. Could you also add that to the tooltip @mvl22 ?

Good catch.

**Comment by mvl22** [comment]
Thanks - fixed in #263. Good to get this terminology clear.

**Comment by Robinlovelace** [comment]
Great work @mvl22. See my suggested changes in the PR. Thanks for attention to detail, very much appreciated.

**Comment by mvl22** [comment]
Ready for merging, with your latest changes included.
