### ISSUE TITLE
Update CBD layer with new data

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#267]
Please @wangzhao0217 and @juanfonsecaLS1 can you do a quick check of the data: https://nptscot.blob.core.windows.net/pmtiles/cbd_layer_2024-11-01.pmtiles

Assuming we get 👍 from at least one of you guys, @mvl22 can you get this on our test site, replacing the old dataset, asap?

**Comment by Robinlovelace** [comment]
Many thanks for the heads-up Juan, will check it out and update..

**Comment by mvl22** [comment]
Lemme know when that's corrected with a further release and I'll update.

**Comment by Robinlovelace** [comment]
Working on a fix with Zhao now.

**Comment by Robinlovelace** [comment]
Working on this now, while the data is generating.

**Comment by Robinlovelace** [comment]
My attempts to fix this in related PR not currently working. Checking the data.

Before:

<html><body>

Highway type | unclassified
-- | --
Cycle infrastructure | Mixed Traffic Street
Infrastructure type (detailed) | undefined
Average daily motor traffic | 4,932
Speed limit | 20mph
Level of Service | Low
OpenStreetMap ID | Way #2956326


</body>
</html>Highway type 	unclassified
Cycle infrastructure 	Mixed Traffic Street
Infrastructure type (detailed) 	undefined
Average daily motor traffic 	4,932
Speed limit 	20mph
Level of Service 	Low
OpenStreetMap ID 	[Way #2956326](https://www.openstreetmap.org/way/2956326/)

**Comment by Robinlovelace** [comment]
After: 

Infrastructure type
Level of Service
Speed limit
Traffic volume category
highway
osm_id

**Comment by Robinlovelace** [comment]
Fixed:

![image](https://github.com/user-attachments/assets/336cc392-43ab-478e-9389-e95dd8f7fdd0)


In #268 running locally. Let's get this on the test website ASAP.

**Comment by Robinlovelace** [comment]
One note on the data: technically some of the roads are not estimated but based on actual DfT counts (most of the big roads). We could signal that these values are observed not modelled. In practice I don't think the benefits of doing this are big: the most important thing is whether the traffic is high-enough to need infrastructure given speeds and for the major roads the levels of traffic are often off that scale (4000+). Interested to hear what you think about this distinction in any case @juanfonsecaLS1.
