### ISSUE TITLE
Remove popups for schools for now

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#273]
As we have done with zones, to be consistent. We can re-add at a later date if needs be.

One non-removing popup option: keep the school name and total number of pupils.

Thoughts @mvl22 ? Should be a quick one and make the codebase a bit simpler and more internally consistent.

**Comment by mvl22** [comment]
Is there a downside to having the data? Obviously if it's wrong or problematic it should be removed, but I wouldn't remove it entirely purely for a reason of other data not being there.

I don't think it's problematic for some layers not to have popups.

**Comment by Robinlovelace** [comment]
Yes, the data is not right atm.
