### ISSUE TITLE
Update additional files for December

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#276]
As shown below:

![image](https://github.com/user-attachments/assets/f70fc8bc-5dce-4137-920f-8430ab65760b)

One file that's worth uploading later is 

- [ ] CBD file, to fix the issue with traffic level on Leith Walk

Can you give that a go @wangzhao0217? See preview PRs like #270 to see which files to edit, there should just be 1 file and 5 lines of code in this case, you can open a PR when ready.

**Comment by mvl22** [comment]
Is this all now resolved, after the various commits and typo fixes?

**Comment by Robinlovelace** [comment]
Yes, cheers, for nudge.
