### ISSUE TITLE
Traffic layer is hard to find, how best to make it easier to find?

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#277]
As discussed today during ad-hoc user testing session with @Hussein-Mahfouz, the traffic layer is hard to find. It reminds of the Travel to School layer in the PCT, where the functionality was so hidden that people ended up not using it. As a new user, how would you possibly know to look in "Cycling by Design" if you were looking for current traffic levels?

Unlike many users, Hussein was actually trying to find it and even after a few minutes of clicking around could not (found now with guidance from me during ad-hoc testing).

I'm not sure how best to address this, but simple is good and a safe change would be to simply change the heading of the layer from 

```
Cycling by Design compliance
```

to

```
Level of Service, Traffic, and Infrastructure
```

What do people think? I think naming the widget by its purpose and functionality rather than by the perhaps rather esoteric name of the report on which it is based, could be a quick fix, that actually mentions traffic.

**Comment by mvl22** [comment]
I would use 'Existing infrastructure' - I think the proposed label is a bit unwieldy.

**Comment by Robinlovelace** [comment]
Even better:

`Infrastructure and Traffic`

"existing" is a bit redundant IMO.

**Comment by Robinlovelace** [comment]
Or:

```
Infrastructure, Traffic, and Compliance
```

**Comment by Robinlovelace** [comment]
Or:

```
Infrastructure, Traffic, and Level of Service
```

**Comment by Robinlovelace** [comment]
All the proposed solutions are quick, will give this one a bash. I've just created a linked branch with

```
gh issue develop 277 --checkout
```
