### ISSUE TITLE
Create survey and add links

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#33]
Some people may want to complete a survey to provide feedback without the hassle of creating a GitHub account and opening a public issue. For those people something akin to https://forms.office.com/Pages/ResponsePage.aspx?id=qO3qvR3IzkWGPlIypTW3y9orQ9urif9IgBaXiRS9eEpURURCMEZPVjBRUDg2UTlWSjZYOVlRSU9DTC4u would be helpful.

**Comment by anguscalder** [comment]
Agree - I think most LA officers would find giving feedback via github difficult

**Comment by Robinlovelace** [comment]
Where is the survey? It's good practice to add a comment with context explaining why an issue has been closed. Re-opening for now. Happy for this to be closed when evidence shows it has been (e.g. a link to the survey) or if there's a good explanation, is this issue a duplicate?

**Comment by mem48** [comment]
Done https://forms.office.com/Pages/ResponsePage.aspx?id=qO3qvR3IzkWGPlIypTW3ywVZfmO0bwdAhK0UztpneQtUM1pCRlJQQjY1V0M3MUhBV0g0VTJRS1ZQVi4u

**Comment by Robinlovelace** [comment]
Fantastic! Thanks Malcolm, I should have checked the commit history.
