### ISSUE TITLE
Update branch names

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#37]
I think standard in this case would be something like

- [ ] main where day-to-day development happens, pointing to a dev version hosted at https://nptscot.github.io and now https://nptscot.github.io/web after #36 was fixed
- [x] production which is released periodically after sign-off by more than one person, this would not usually be the default branch

**Comment by Robinlovelace** [comment]
I've renamed the default branch from production to dev so that changes made by people who clone the repo go to the dev environment not production. We should update production with PRs. I don't have an issue with the default branch being called `dev` so closing for now. Any further thoughts welcome @mem48 and others.

**Comment by mem48** [comment]
Please revert this. The was a good reason for doing it that way round. As you can only protect the default branch.

**Comment by Robinlovelace** [comment]
> As you can only protect the default branch.

Are you sure?

**Comment by Robinlovelace** [comment]
We managed to find a way to protect the production branch without it being default. Demo from just now:

```
git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 299 bytes | 299.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/production.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/nptscot/nptscot.github.io.git
 ! [remote rejected] production -> production (protected branch hook declined)
error: failed to push some refs to 'https://github.com/nptscot/nptscot.github.io.git'
(base) ➜  nptscot.github.io git:(production) ✗ 

```

In summary: `dev` is not default branch and `production` is protected. Great work @mem48 on setting this up.
