### ISSUE TITLE
Tile hosting

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#6]
Need long-term solution

Any file server will do, but one that supports FTP access is preferable

**Comment by mem48** [comment]
See #15 

@Robinlovelace for context26:

rnet.pmtiles is currently 26 MB

Google Cloud offers "5 GB-months of regional storage (US regions only) per month" [link](https://cloud.google.com/free/docs/free-cloud-features#free-tier)

Or for UK hosting (recommended for latency)

Google Cloud charge $0.023 per GB/month so rnet hosting would be about $0.007 per year. Extra costs would be associated with uploads and we would also want to enable a CDN https://cloud.google.com/cdn/pricing


Item | Price
Cache egress | $0.02-$0.20 per GiB
Cache fill | $0.01-$0.04 per GiB
HTTP/HTTPS cache lookup requests | $0.0075 per 10,000 requests
Requests sent from Cloud CDN to external backends | Compute Engine  internet egress rates

**Comment by mem48** [comment]
Obviously, other hosts are available and Google Cloud does not support FTP access which is a pain

**Comment by mem48** [comment]
Other datasets are larger e.g. basemap ~ 4GB

**Comment by Robinlovelace** [comment]
Sounds like good value to me! I do think it's likely that Azure via UoL can do this also, cc @sparrow0hawk who we'll discuss this with soon (next week?).

**Comment by Sparrow0hawk** [comment]
Yep meeting about this 3rd March

> Sounds like good value to me! I do think it's likely that Azure via UoL can do this also, cc @Sparrow0hawk who we'll discuss this with soon (next week?).

**Comment by Robinlovelace** [comment]
Next steps on this in prep for meeting tomorrow at 14:00:

- Upload pmtiles files to Azure
- Serve them

**Comment by Robinlovelace** [comment]
Also: we'll need to auto update Azure with each update to a specific branch, e.g. main for dev and prod for production. Easy way to do this bit of DevOps? Imagine so...
