### ISSUE TITLE
Thin lines in rural areas

### ISSUE THREAD

**Issue by mem48** [nptscot/nptscot.github.io#61]
Following discussion with @Robinlovelace a few things about low flow routes

1. Repalce flows 1-9 with default value e.g. 5 and present as <10
2. Make thinnest line thicker so more visible and clickable

**Comment by Robinlovelace** [comment]
Here's a concrete example that we can use to check when this has been fixed.

Before: 

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/8edc342e-9e03-4a4a-9062-91af784b75e7)

Prototype after, what we're aiming towards I think:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/82bc4e8a-2079-4fef-9f2f-898fa0a871ff)


Source: https://www.npt.scot/#9.81/58.535/-3.0823

**Comment by Robinlovelace** [comment]
Can you please show before/after screenshots @mem48 as I have above? And are we closing when fixed on dev or production?

**Comment by Robinlovelace** [comment]
Great to hear it's fixed in any case, will aim to take a look tomorrow.

**Comment by mem48** [comment]
Before

![image](https://github.com/nptscot/nptscot.github.io/assets/15819577/692b7194-3268-4a24-aeb3-947d6a4c6135)

After

![image](https://github.com/nptscot/nptscot.github.io/assets/15819577/9899ceab-858c-4620-beee-32df678285be)

**Comment by Robinlovelace** [comment]
> Surely once fixed in dev we close the issue, otherwise there will be loads of unclosed issues that require no action

:+1:

**Comment by Robinlovelace** [comment]
Looking good. Would be great to see difference for rural area. I'll take a look...

**Comment by Robinlovelace** [comment]
@anguscalder @Mattpdavis ?

**Comment by mem48** [comment]
Also now in dev

![image](https://github.com/nptscot/nptscot.github.io/assets/15819577/c16f8344-a394-4cf9-8be9-96c600890906)

Values less than 10 are replaced in the popup with ≤9

Not in current data actual value is still there. But future builds will replace values 1-9 with a 3.

**Comment by mem48** [comment]
I'm sure our audience with be fine with "less than" it is in KS1 maths!

**Comment by Mattpdavis** [comment]
From the partner webinar the main thing for me was to make the lowest flows more visible, in colour and/or width, so they're easier to click on and more obviously different from 0.
I'm less bothered on what the display number is. I'm probably happy with showing the actual number but will go with Angus' decision.
