### ISSUE TITLE
Separate primary and secondary networks

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#68]
This is the UI component of https://github.com/nptscot/npt/issues/186, which needs to be fixed before this can be tackled. I'm not 100% sure if this is in scope and only worth exploring after https://github.com/nptscot/npt/issues/186 has been tackled.

**Comment by mem48** [comment]
Done but primary and secondary networks look the same. Bug?

**Comment by Robinlovelace** [comment]
> Done but primary and secondary networks look the same. Bug?

Sounds like a bug.

**Comment by mem48** [comment]
Now fixed
