### ISSUE TITLE
More elegant solution to get the date of OSM updates

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#77]
Currently we have:

https://github.com/nptscot/nptscot.github.io/blob/c2bead98f5bf4285c41d3aa3a4b23d08eac5bd0f/js/welcome.js#L15-L26

Would be better to have something a bit more concise, as discussed with @mem48.

**Comment by Robinlovelace** [comment]
Note: routing date can be found here https://github.com/nptscot/npt/blob/main/outputs/build_summary.csv

From here: https://github.com/nptscot/npt/blob/4bc63335b31680f0f489dbf71a086d7049fdb01e/_targets.R#L504C27-L504C27

**Comment by mem48** [comment]
Done

**Comment by Robinlovelace** [comment]
What was the change?

**Comment by Robinlovelace** [comment]
Hardcoding it as

```js
document.getElementById("osmupdatedate").innerHTML = '5th August 2023'
```

doesn't seem particularly elegant. But it works.

https://github.com/nptscot/nptscot.github.io/commit/ddce522563656ce60f1d4dd00e27eb89509a7529
