### ISSUE TITLE
Update user manual to incorporate changes in v0.2

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#83]
As discussed with @mem48 and @anguscalder, the old manual does not have all the latest updates. Aim: get this done by end of play Thursday next week. Let us know @juanfonsecaLS1 and @wangzhao0217 if you would like to try this and we can point you in the right direction. Otherwise me and @mem48 can give it a go, will let you lead on this for now Malcolm.

**Comment by wangzhao0217** [comment]
Hi Robin,
I will contribute to update.
Regards,
Zhao
