### ISSUE TITLE
Add version

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#92]
Currently the version is out-of-date. We should have a proper versioning system and release 0.2 I think.

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/5262c9e5-590a-42ce-a134-14401b75b468)

**Comment by Robinlovelace** [comment]
I don't think this is done because the versions are not linked to GitHub releases and we're not versioning the UI repo. See here for details of what I'm thinking: https://semver.org/

**Comment by mem48** [comment]
This was a wontifx

**Comment by Robinlovelace** [comment]
Why? It's widely seen as good practice to have version numbers and wouldn't be a huge amount of work.
