### ISSUE TITLE
Changing basemap causes all layers to reload

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#94]
Reproducible example: go to https://www.npt.scot/#10.67/55.9292/-3.11 and change the basemap.

Opening now because it seems there is a solution. As described by @dabreegster in https://github.com/acteng/atip/pull/351 and shown in the videos it is possible to prevent the whole page reloading.

I tested it at https://acteng.github.io/atip/swap_basemap/browse.html and noticed that the other layers still temporarily disappear. If I recall correctly in leaflet basemap changes I've seen there is no disappearance of other layers. In any case it seems quicker and as Dustin says may be useful for this project. Thoughts @mem48? Not a priority and not sure how big the UX benefit will be compared with time cost of fixing this and probably not a priority.

**Comment by dabreegster** [comment]
You can also follow https://docs.mapbox.com/mapbox-gl-js/example/style-switch/ to get the same effect. The benefit of the approach in https://github.com/dimfeld/svelte-maplibre/pull/60 (the source of this trick) is that it's agnostic to your own code structure for how sources and layers get added.

> noticed that the other layers still temporarily disappear

I think that's inevitable with MapLibre's design

**Comment by mem48** [comment]
I agree with @dabreegster there is no way in Maplibre to change the base map without reloading all the layers, especially with the deep integration between data and basemap in npt.scot
