### ISSUE TITLE
Landing page tweaks

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/nptscot.github.io#99]
Currently we have this:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/8d6a79d0-8ddd-4ad2-babd-5d6c6d76dd15)

We should:

- [ ] Remove the white vertical bar
- [x] Update the logo in the top right: a meta-logo?
- [ ] Change the colour of the top bar, currently dark grey

**Comment by Robinlovelace** [comment]
Only one of the three sub-issues has been fixed:

![image](https://github.com/nptscot/nptscot.github.io/assets/1825120/eaa8d928-517f-492e-ae4c-4d5697f2cc4d)

The vertical white bar is a bug, I think we agreed to change the colour of the top bar, but happy to wait for further feedback on that.

**Comment by mem48** [comment]
The vertical line is not a bug, and we agreed to keep the bar gey
